[package]
name = "rack"
version = "0.1.0"
edition = "2021"
authors = ["Cas Brugman <casbrugman@hotmail.nl>"]

[dependencies]
biquad = "0.4.2"
cpal = "0.15.2"
dyn-clone = "1.0.11"
indexmap = "1.9.3"
rand = "0.8.5"
rfd = "0.11.4"
ringbuf = "0.3.2"
rubato = "0.12.0"
strum = { version = "0.24.1", features = ["strum_macros"] }
strum_macros = "0.24.3"


[dependencies.symphonia]
version = "0.5.2"
features = ["mp3"]

[dependencies.eframe]
version = "0.22.0"
default-features = false
features = ["default_fonts", "glow"]

[dependencies.uuid]
version = "1.3.0"
features = ["v4"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3


